apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-demo-cert
spec:
  secretName: cm-demo-cert-secret
  dnsNames:
  - "dev.adrz.dev"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer